package com.sawyereffect.core.servlets;

import org.apache.felix.scr.annotations.sling.SlingServlet;
import org.apache.sling.api.SlingHttpServletRequest;
import org.apache.sling.api.SlingHttpServletResponse;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.api.servlets.SlingSafeMethodsServlet;

import javax.servlet.ServletException;
import java.io.IOException;

@SuppressWarnings("serial")
@SlingServlet(resourceTypes = "apps/structure/page")
public class SimpleServlet extends SlingSafeMethodsServlet {

  @Override
  protected void doGet(final SlingHttpServletRequest request,
                       final SlingHttpServletResponse response) throws ServletException, IOException {

    response.getOutputStream().println(
            "This content is generated by the SimpleServlet");
  }
}

